name: linkjo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  audioplayers: ^6.1.0
  geolocator: ^13.0.1
  web_socket_channel: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
